services:
  api:
    build: .
    container_name: currency-exchange-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/currency_exchange
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    depends_on:
      mongo:
        condition: service_healthy
      mailhog:
        condition: service_started

  mongo:
    image: mongo:7
    container_name: currency-exchange-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Fake SMTP server. UI en :8025.
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: currency-exchange-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

volumes:
  mongo-data:
